import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Model from "./components/modals/Modal";
import LoginModal from "./components/modals/LoginModal";
// import SearchModal from "./components/modals/SearchModal";
import SignupModal from "./components/modals/SignupModal";
// import AddPropertyModal from "./components/modals/AddPropertyModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DjangoBnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        
        <div className="pt-32">
          {children}
        </div>


         <LoginModal />
        <SignupModal />
         {/* <SearchModal />
        <AddPropertyModal />  */}
      </body>
    </html>
  );
}
